### PR TITLE
First pass at GPX config file generation

### PR DESCRIPTION
**Pull request by d235j**
This is a first attempt that seems to generate workable results. It certainly is not ready to merge.

Printer and extruder definitions for a Makerbot Replicator 2X to work with this can be found at https://gist.github.com/d235j/06f9f1d98cd8cd337663f7855e8ecb43.

### CODE REVIEW

**Comment by d235j** [comment]
Motivation: A small group including myself has been working on mods to the Replicator 2 and 2X series to improve the printer's usability. A major issue has been lack of sufficient torque from the extruder motor, which can be solved by adding a geared-down extruder. However, this changes the extruder steps/mm. Therefore it is very helpful to have these steps/mm parameters in the printer and extruder definitions.

**Comment by Ghostkeeper** [comment]
Ah, I was still planning on adding these settings to the actual definitions in Cura. I hoped to get that done last weekend, but didn't get around to it.

**Comment by d235j** [comment]
@Ghostkeeper this does add the settings to the actual definitions in Cura — though it does so in a rather hackish way and I'm sure there's a superior way to do it.

**Comment by d235j** [comment]
@Ghostkeeper any plans to continue with this or suggestions on a cleaner way to do this? Thanks!

**Comment by Ghostkeeper** [comment]
I think I'm going to get a pull request in at the main Cura repository to add our settings to the actual printer definitions. That's a much cleaner way to approach this, because different printers can then have different default settings for GPX. And also, they can be machine settings that are hidden to the user interface. Perhaps you could help me test it on an actual printer though, afterwards?

**Comment by Ghostkeeper** [comment]
Sorry that it took so long. There's a lot of things going on for me right now.

**Pull request closed without merging**
